server:
  port: 80
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
spring:
  application:
    name: cloud-consumer-hystrix-order
#设置Feign客户端超时时间（OpenFeign默认支持Ribbon）
#ribbon:
  #  指的是建立连接所用的时间，适用于网路状态正常的情况下，两端连接所用的时间
#  ReadTimeout: 5000
  #  指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000
#  支持hystrix
feign:
  hystrix:
    enabled: true